### ISSUE TITLE
Units for distance

### ISSUE THREAD

**Issue by CrashOverride90** [evermeer/EVFaceTracker#1]
Could you clarify what the units are for the recorded distance in the code?

**Comment by evermeer** [comment]
OK, Here is an explanation:

**fluidUpdate:**
When using face detection, the number of updates per second is not enough to give you a rectangle that does not vary too much. In order to overcome that I added an extra loop. In the sample it will always be triggered 20 times a second. This is initiated with this code:
    [evFaceTracker fluidUpdateInterval:0.05f withReactionFactor:0.3f];
This will make sure that it will go a little more fluent from one rectangle to the next using interpollation. How fast it will go to the new rectangle depends on the factor. Here it's set to 0.3.  That is good enough for most cases. You could play around to see what happens with an other factor.

**faceIsTrackedParameters:**
The faceIsTracked function will be called after every face detection change. When it's called depends on iOS. Most of the parameters there come directly from the face detection api or are calculated using a simple function.
- faceRect = the rectangle that is detected by the face detection api
- offsetWidth = how much is the rectangle off center horizontally (is 0 when your face is in the center, its minus when you tilt your phone right, positive it you tilt the phone left)
- offsetHeight = how much is the rectangle off center vertically (is 0 when your face is in the center, its minus when you tilt your phone up, positive it you tilt the phone down)
- distance = It's an estimated distance in centimeters. the calculation is based on the rectangle size. So in theory it's only good for an average head size :-)
